import {Inter} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "@/components/utils/ThemeProvider";
import ThemeToggle from "@/components/utils/ThemeToggle";

const inter = Inter({
  variable: "--font-family-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} antialiased`}
      >
        <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTrasitionOnChange
        >
            <div className="bg-body-background min-h-screen font-inter">
                {children}
                <ThemeToggle className='fixed top-3 right-3 z-50'/>
            </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
