
### C Run code Request (Accepted) ###

POST http://localhost:8080/problems/10/run
Authorization: Bearer 12345678
Content-Type: application/json

{
    "userCode": "int addTwo(int a, int b) {\n\treturn a+b;\n}",
    "language": "c",
    "userTestcases": []
}

### C Run code Request (Compilation Error) ###

POST http://localhost:8080/problems/10/run
Authorization: Bearer 12345678
Content-Type: application/json

{
    "userCode": "int addTwo(int a, int b) {\n\treturn a+b\n}",
    "language": "c",
    "userTestcases": []
}

### C Run code Request (Time Limit Exceeded) ###

POST http://localhost:8080/problems/10/run
Authorization: Bearer 12345678
Content-Type: application/json

{
    "userCode": "int addTwo(int a, int b) {\n\t while(1){} \n\t return a+b;\n}",
    "language": "c",
    "userTestcases": []
}

### Cpp Run code Request (Accepted) ###

POST http://localhost:8080/problems/10/run
Authorization: Bearer 12345678
Content-Type: application/json

{
    "userCode": "int addTwo(int a, int b) {\n\treturn a+b;\n}",
    "language": "cpp",
    "userTestcases": []
}

### Cpp Run code Request (Compilation Error) ###

POST http://localhost:8080/problems/10/run
Authorization: Bearer 12345678
Content-Type: application/json

{
    "userCode": "int addTwo(int a, int b) {\n\treturn a+b\n}",
    "language": "cpp",
    "userTestcases": []
}

### Cpp Run code Request (Time Limit Exceeded) ###

POST http://localhost:8080/problems/10/run
Authorization: Bearer 12345678
Content-Type: application/json

{
    "userCode": int addTwo(int a, int b) {\n\t while(1){} \n\t return a+b;\n}",
    "language": "cpp",
    "userTestcases": []
}

### Java Run code Request (Accepted) ###

POST http://localhost:8080/problems/10/run
Authorization: Bearer 12345678
Content-Type: application/json

{
    "userCode": "class Solution {\npublic int addTwo(int a, int b) {\nreturn a+b;\n\n}\n}",
    "language": "java",
    "userTestcases": []
}

### Java Run code Request (Compilation Error) ###

POST http://localhost:8080/problems/10/run
Authorization: Bearer 12345678
Content-Type: application/json

{
    "userCode": "class Solution {\npublic int addTwo(int a, int b) {\nwhile(true) {} \nreturn a+b;\n\n}\n}",
    "language": "java",
    "userTestcases": []
}

### Java Run code Request (Time Limit Exceeded) ###

POST http://localhost:8080/problems/10/run
Authorization: Bearer 12345678
Content-Type: application/json

{
    "userCode": "class Solution {\npublic int addTwo(int a, int b) {\nif(a%2==0 || b%2==0){ while(true) {} }\nreturn a+b;\n\n}\n}",
    "language": "java",
    "userTestcases": []
}

### Javascript Run code Request (Accepted) ###

POST http://localhost:8080/problems/10/run
Authorization: Bearer 12345678
Content-Type: application/json

{
    "userCode": "function addTwo(a, b) {\n\treturn a+b;\n}",
    "language": "javascript",
    "userTestcases": []
}

### Python Run code Request (Accepted) ###

POST http://localhost:8080/problems/10/run
Authorization: Bearer 12345678
Content-Type: application/json

{
    "userCode": "def addTwo(a, b):\n\treturn a+b",
    "language": "python",
    "userTestcases": []
}