spring:
  application:
    name: C-EXECUTION-SERVICE

  cloud:
    consul:
      host: ${CODEHORN_CONSUL_HOST:localhost}
      discovery:
        service-name: C-EXECUTION-SERVICE
        healthCheckPath: /health-check   # 👈 Custom health check path
        healthCheckInterval: 15s