spring:
  application:
    name: CODE-EXECUTION-SERVICE

  cloud:
    consul:
      host: ${CODEHORN_CONSUL_HOST:localhost}
      discovery:
        service-name: CODE-EXECUTION-SERVICE
        healthCheckPath: /health-check   # 👈 Custom health check path
        healthCheckInterval: 15s