spring:
  application:
    name: PROBLEMS-SERVICE

  cloud:
    consul:
      host: ${CODEHORN_CONSUL_HOST:localhost}
      discovery:
        service-name: PROBLEMS-SERVICE
        healthCheckPath: /health-check   # 👈 Custom health check path
        healthCheckInterval: 15s

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console