name: Run Application Test

on:
  workflow_dispatch:

jobs:
  test-application:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: 'local-test'

      - name: Change Gradle-wrapper Properties
        run: |
          cat <<EOF > ./gradle/wrapper/gradle-wrapper.properties
          distributionBase=GRADLE_USER_HOME
          distributionPath=wrapper/dists
          distributionUrl=https\\://services.gradle.org/distributions/gradle-8.11-bin.zip
          networkTimeout=10000
          validateDistributionUrl=true
          zipStoreBase=GRADLE_USER_HOME
          zipStorePath=wrapper/dist
          EOF
        working-directory: backend

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Testing the Services
        run: ./gradlew clean test
        working-directory: backend