name: Start Test Deployment

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: 'local-test'

      - name: Change Gradle-wrapper Properties
        run: |
          cat <<EOF > ./gradle/wrapper/gradle-wrapper.properties
          distributionBase=GRADLE_USER_HOME
          distributionPath=wrapper/dists
          distributionUrl=https\\://services.gradle.org/distributions/gradle-8.11-bin.zip
          networkTimeout=10000
          validateDistributionUrl=true
          zipStoreBase=GRADLE_USER_HOME
          zipStorePath=wrapper/dist
          EOF

      - name: Verify Gradle-wrapper Properties Update
        run: cat ./gradle/wrapper/gradle-wrapper.properties

      - name: Change Backend of Terraform
        run: |
          touch ./terraform/local-cloud-deployment/backend.tf
          cat <<EOF > ./terraform/local-cloud-deployment/backend.tf
          terraform {
             required_version = ">= 1.0.0"
             required_providers {
               aws = {
                 source = "hashicorp/aws"
                 version = "~> 4.0"
               }
             }
             backend "s3" {
               bucket  = "${{ secrets.TEMP_TERRAFORM_STATE_BUCKET }}"
               key     = "terraform/terraform.tfstate"
               region  = "${{ secrets.AWS_NAJIMA_REGION }}"
               encrypt = true
             }
          }
          EOF

      - name: Verify Backend of Terraform Update
        run: cat ./terraform/local-cloud-deployment/backend.tf

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build All Services
        run: ./gradlew clean build -x test

      - name: Setup AWS CLI
        run: |
          sudo apt-get update -y
          aws --version
          aws configure set aws_access_key_id ${{ secrets.AWS_NAJIMA_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_NAJIMA_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_NAJIMA_REGION }}

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.AWS_KEY_PAIR_SSH }}" > NajimaBanuKeyPair.pem
          chmod 600 NajimaBanuKeyPair.pem

#      - name: Upload JARs to S3
#        run: |
#          for jar in service1 service2 service3 service4; do
#            aws s3 cp $jar/build/libs/$jar-1.0.0.jar s3://${{ secrets.S3_BUCKET }}/$jar.jar
#          done

      - name: Upload JARs to S3
        run: |
          aws s3 mb s3://${{ secrets.TEMP_S3_BUCKET }}
          for jar in java-execution-service; do
            aws s3 cp $jar/build/libs/$jar-1.0.0.jar s3://${{ secrets.TEMP_S3_BUCKET }}/$jar.jar
          done

      - name: Create backend for terraform in s3
        run: aws s3 mb s3://${{ secrets.TEMP_TERRAFORM_STATE_BUCKET }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init terraform
        run: terraform init
        working-directory: terraform/local-cloud-deployment

      - name: Validate Terraform
        run: terraform validate
        working-directory: terraform/local-cloud-deployment

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: terraform/local-cloud-deployment
