name: Stop Test Deployment

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Start Test Deployment"]
    types:
      - completed

jobs:
  delete-sources:
    if: >
      (github.event_name == 'workflow_dispatch') || 
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'failure')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: 'local-test'

  destroy-terraform:
    if: github.event.workflow_run.conclusion == 'failure' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: 'local-test'

      - name: Change Backend of Terraform
        run: |
          touch ./terraform/local-cloud-deployment/backend.tf
          cat <<EOF > ./terraform/local-cloud-deployment/backend.tf
          terraform {
             required_version = ">= 1.0.0"
             required_providers {
               aws = {
                 source = "hashicorp/aws"
                 version = "~> 4.0"
               }
             }
             backend "s3" {
               bucket  = "${{ secrets.TEMP_TERRAFORM_STATE_BUCKET }}"
               key     = "terraform/state.tfstate"
               region  = "${{ secrets.AWS_NAJIMA_REGION }}"
               encrypt = true
             }
          }
          EOF

      - name: Verify Backend of Terraform Update
        run: cat ./terraform/local-cloud-deployment/backend.tf

      - name: Setup AWS CLI
        run: |
          sudo apt-get update -y
          aws --version
          aws configure set aws_access_key_id ${{ secrets.AWS_NAJIMA_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_NAJIMA_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_NAJIMA_REGION }}

      - name: Create backend for terraform in s3
        run: aws s3 mb s3://${{ secrets.TEMP_TERRAFORM_STATE_BUCKET }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init terraform
        run: cd ./terraform/local-cloud-deployment && terraform init && cd ../../

      - name: Delete backend for terraform in s3
        run: aws s3 rb s3://${{ secrets.TEMP_TERRAFORM_STATE_BUCKET }} --force